org.gradle.jvmargs=-Xmx2G -XX:+UseParallelGC -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft properties
minecraft_version = 1.21.1
enabled_platforms = fabric,neoforge

# Mod properties
mod_version = 1.4.0.2637.2
maven_group = com.blackgear
archives_name = Platform
mod_id = platform

# Dependencies
architectury_api_version = 13.0.8
parchment_version=2024.11.17

fabric_loader_version = 0.16.12
fabric_api_version = 0.115.4+1.21.1

neoforge_version = 21.1.84